version: '3.2'

services:
  graphqlservice:
    image: xfilefin/battlemanager-graphqlservice:latest
    ports:
      - "4000:4000"
    environment:
      APP_KEY: battlemanager-development
      COOKIE_SECRET: battlemanager-development
      ACCESS_TOKEN_SECRET_KEY: battlemanager-development
      ACCESS_TOKEN_LIFE: 300
      REFRESH_TOKEN_SECRET_KEY: battlemanager-development
      REFRESH_TOKEN_LIFE: 86400
      ALLOWED_ORIGINS: http://localhost:3000,https://studio.apollographql.com
      DATABASE_URL: mysql://dbusername:dbpassword@dbhostname:3306/dbname
      INTERNAL_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@battlemanager.com
      ADMIN_PASSWORD: adminpassword

  managementfrontend:
    image: xfilefin/battlemanager-managementfrontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js

  rconconnector:
    image: xfilefin/battlemanager-rconconnector:latest
    # ports:
    #   - "8080:8080"
    environment:
      RCON_IPPORT: 127.0.0.1:47200
      RCON_PASSWORD: rconadminpassword
      BACKEND_ENDPOINT: http://graphqlservice:4000
      HOST_HOSTNAME: http://rconconnector:8080
      INTERNAL_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      RUST_LOG: debug
